name: test_1
on:
  push:
    branches:
      - main
#    tags:
#      - '*'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Install package
        run: npm install
        
      - name: Build website
        run: npm run build
        
      - name: Depoly to server
        uses: up9cloud/action-rsync@v1.4
        with:
          switches: -arH
          path: ./
          remote_host: ${{ vars.SERVER_IP }}
          remote_port: ${{ vars.SERVER_PORT }}
          remote_user: ${{ vars.SERVER_USERNAME }}
          remote_path: ${{ vars.SERVER_DESTINATION }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
          
      - name: Restart server service
        uses: tiyee/action-ssh@v1.0.1
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SERVER_USERNAME }}
          port: ${{ vars.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo systemctl stop ${{ vars.SERVER_SERVICE_NAME }}
            rm -rf ${{ vars.SERVER_SERVICE_WORKDIR }}
            mv ${{ vars.SERVER_DESTINATION }} ${{ vars.SERVER_SERVICE_WORKDIR }}
            sudo systemctl start ${{ vars.SERVER_SERVICE_NAME }}   
